[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
gas_reports = ["*"]

# Solidity compiler
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# test configuation
[fuzz]
runs = 256
seed = "0"

# test report
[fmt]
line_length = 120
tab_width = 4

# test filter
[invariant]
runs = 256
depth = 30
fail_on_revert = false
call_override = false

# RPC
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "https://mainnet.optimism.io"
arbitrum = "https://arb1.arbitrum.io/rpc"

# ethereum explorer API
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }